version: 0.0 
os: linux
files:
  - source: https://github.com/AdvaitKukade/CirclediCodeDeploy.git
  - destination: /var/www/html
hooks:
  BeforeInstall: 
    - location: scripts/install_apache.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/restart_apache.sh
      timeout: 300
      runas: root