version: 2.1
workflows:
  deploy_application:
    jobs:
      - aws-code-deploy/deploy:
          application-name: HTMLTRY2
          aws_default_region: ap-south-1
          deployment-group: HTMLTRY2DG
          service-role-arn: arn:aws:iam::760603953831:role/CodeDeployServiceRole2
          bundle-bucket: htmlmybucket1
          bundle-key: Htmlfiles.zip
          arguments: 'region: ${AWS_DEFAULT_REGION}'
orbs:
   aws-code-deploy: circleci/aws-code-deploy@0.0.10
